### ISSUE TITLE
Ubuntu xenial got "ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk" error when run gralde in container .

### ISSUE THREAD

**Issue by lidaling** [keeganwitt/docker-gradle#230] opened 2022-09-18 04:31 UTC
ubuntu xenial has the same error when run gralde in container .

Dockerfile as bellow:
```
FROM gradle:jd8 AS build
WORKDIR /build
COPY . .
RUN ls -al /opt
RUN gradle
```

_Originally posted by @lidaling in https://github.com/keeganwitt/docker-gradle/issues/227#issuecomment-1250188480_

**Comment by lidaling** [comment] 2022-09-18 04:49
Using gradle:jdk8-focal is OK.
But I want to know why ? "ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk"  error casued by host docker version ? or system ?

**Comment by keeganwitt** [comment] 2022-09-19 16:58
The error message is misleading, but unfortunately outside my ability to remedy.

The reason is discussed in this comment: https://github.com/adoptium/containers/issues/215#issuecomment-1142046045, which was caused by a change in Docker https://github.com/moby/moby/commit/9f6b562dd12ef7b1f9e2f8e6f2ab6477790a6594 which is incompatible with images using Ubuntu Jammy.

That comment also mentioned a workaround with a security policy, but I haven't tested that.

**Comment by keeganwitt** [comment] 2022-09-19 17:00
Closing issue as a duplicate of #226 and #227.

**Closed by keeganwitt** 2022-09-19 17:00 UTC

**Comment by keeganwitt** [comment] 2022-10-14 18:55
This issue has come up so frequently (#221, #222, #223, #224, #226, #227, #230, #231), I've created a page explaining: https://github.com/keeganwitt/docker-gradle/wiki/Troubleshooting:-JAVA_HOME-is-set-to-an-invalid-directory. Please let me know how the page can be improved.
