### ISSUE TITLE
Problems pulling the image

### ISSUE THREAD

**Issue by hm1rafael** [keeganwitt/docker-gradle#67] opened 2018-08-28 17:10 UTC
Trying to docker pull gradle:alpine

throws this error:
alpine: Pulling from library/gradle
no matching manifest for unknown in the manifest list entries

Other images (not gradle) are normal

**Comment by hm1rafael** [comment] 2018-08-28 17:20
Apparently duplicate of #66

**Comment by piclemx** [comment] 2018-08-28 18:32
Got the same problem here

**Comment by hm1rafael** [comment] 2018-08-28 18:52
Using ```gradle:4.9-alpine``` for the time being

**Comment by keeganwitt** [comment] 2018-08-28 19:52
Closing as dupe of #66.

**Closed by keeganwitt** 2018-08-28 19:52 UTC
