### ISSUE TITLE
 how start gradle daemon

### ISSUE THREAD

**Issue by StephanPraetsch** [keeganwitt/docker-gradle#131] opened 2020-02-29 12:24 UTC
Hi,

thanks for providing this. I use
```
FROM gradle:5.6.3-jdk8
MAINTAINER stephan.praetsch <stephan.praetsch@mercateo.com>

RUN gradle --daemon
```

unfortunately it doesn't start the daemon. Each time I execute a gradle command it prints

```
Starting a Gradle Daemon (subsequent builds will be faster)
```

The `RUN gradle --daemon` command is pretty quick done during the docker build. When I execute that command in a running container it takes a while (10 - 30 seconds) and I see a progress. So I doubt the command is executed well.

Thus I'm helpless for now how to start the gradle daemon during creation of the docker image.

**Comment by keeganwitt** [comment] 2020-03-01 17:54
I'm honestly not a complete expert when it comes to the internals of how the daemon works.  However, I do know that it saves things like PIDs, statuses, etc.  Using [Dive](https://github.com/wagoodman/dive) to look at what files change when `gradle --daemon` is run, I see

![image](https://user-images.githubusercontent.com/64612/75629853-b14b5800-5bb3-11ea-8e5e-c3045471aaab.png)

And that the following Gradle command (`gradle --status` in this case), removes the previously added file.

![image](https://user-images.githubusercontent.com/64612/75629897-2880ec00-5bb4-11ea-9eaa-5602017d1e62.png)

I think the problem is related to the fact all Docker layers are immutable, yet mutable state files are necessary for the daemon to do what it needs to do.  Very often in CI and container/image contexts, the daemon is disabled because the nature of the environment precludes the possibility of the daemon being re-used (e.g. the VM is torn down, container destroyed, image layer no longer writable, etc).

If you really need to re-use the daemon, I think you'll need to place the directory where the daemon keeps it's state into a volume, so that it can continue to be written to between image layers and/or containers (i.e., make it mutable).

Another thing to consider is if you make sure to run any invocations using the daemon in the same layer, it will be able to re-use that daemon, for example if you do
```
RUN gradle --daemon > /dev/null && gradle --status
```
instead of
```
RUN gradle --daemon
RUN gradle --status
```
You can see the daemon will be seen
```
Step 2/2 : RUN gradle --daemon > /dev/null && gradle --status
 ---> Running in f41cb79d5cc7
   PID STATUS   INFO
    32 IDLE     6.2.1

Only Daemons for the current Gradle version are displayed. See https://docs.gradle.org/6.2.1/userguide/gradle_daemon.html#sec:status
Removing intermediate container f41cb79d5cc7
 ---> b730a8314897
```

**Comment by aka-bash0r** [comment] 2021-05-13 14:36
In Dockerfiles, `RUN` commands are executed while *building* a docker image. You try to start the docker daemon while *building* the image and expect it to still run on the actual start of the image (aka `docker run --rm -u gradle -v "$PWD":/home/gradle/project -w /home/gradle/project gradle <gradle command>`).

**Comment by keeganwitt** [comment] 2021-05-13 21:40
That's true too. I was trying to think of a way to have the process restart again, while using the previous state. But that's probably not a good idea anyway. It's better to let Gradle manage it's own daemon processes, the way it was designed to. I think I'll close this issue at this time.

**Closed by keeganwitt** 2021-05-13 21:40 UTC
